import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Navbar } from '../components/Navbar'
import Footer from '../components/Footer'
import OfertaCard from '../components/OfertaCard'
import { FaPhone } from 'react-icons/fa'

export default function Home() {




  return (
    <>
      <Head>
        <title>Nord Szczecin - Kuchnie na wymiar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Header wiht navbar*/}

      <Navbar />

      {/*Main content*/}
      <div className={[styles['main-container'], ['content-container']].join(' ')}>

        {/*Title image*/}
        {/*Hero section*/}
        <div id='home' className={[styles['hero-section'],styles['img1']].join(" ")}>
          <div className={styles['hero-section-text']} >Kuchnie na wymiar</div>
          <div id='animated-text' className={styles['hero-section-text-animated']}>
            <span>Nowoczesne i stylistyczne rozwiązania</span>
          </div>
        </div>


        {/*Head of the page with main text and call to action*/}

        
      </div>



      {/*Footer*/}

      <Footer />


    </>
  )
}
