import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { NavbarSinglePage } from '../components/Navbar'
import Footer from '../components/Footer'
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Nord Szczecin - Kuchnie na wymiar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Header wiht navbar*/}

      <NavbarSinglePage />

      {/*Main content*/}
      <div className={[styles['main-container'], ['content-container']].join(' ')}>
        {/*Title image*/}
        <div id='home' className={styles['article-image-container']}>
          <Image
            className={styles["custom-img"]}
            src={"/res/1.jpg"}
            layout='fill'
            alt=""
            objectFit='cover'
          />
        </div>
        {/*Head of the page with main text and call to action*/}

        <div id='oferta' className={styles['section']}>
          <h1>Oferta</h1>
        </div>
        <div id='realizacje' className={styles['section']}>
          <h1>Realizacje</h1>
        </div>
        <div id='kontakt' className={styles['section']}>
          <h1>Kontakt</h1>
        </div>
      </div>



      {/*Footer*/}

      <Footer />


    </>
  )
}
