import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Navbar } from '../components/Navbar'
import Footer from '../components/Footer'
import OfertaCard from '../components/OfertaCard'
import { FaPhone } from 'react-icons/fa'
import { useWindowSize } from '../utils/CustomHooks'

export default function Kontakt() {


{/*Custom hook responsible for detecting small screen like mobiles*/ }
const size = useWindowSize();

    return (
        <>
            <Head>
                <title>Nord Szczecin - Kuchnie na wymiar</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/*Header wiht navbar*/}

            <Navbar />

            {/*Main content*/}
            <div className={[styles['main-container'], ['content-container']].join(' ')}>
                <div id='home' className={[styles['hero-section'],styles['img1']].join(" ")}>
                    <div className={styles['hero-section-text']} >Skontaktuj się z nami</div>
                    {size.width > 600 ? 
                    <>
                    <div id='animated-text' className={styles['hero-section-text-animated']}>
                        <div className={styles['kontakt-content']}>Nasza oferta obejmuje projektowanie, produkcję i montaż mebli, takich jak meble kuchenne, szafy, garderoby oraz meble biurowe w województwie <span className={['accent']}>Zachodniopomorskim</span>.</div>
                        <div className={styles['kontakt-content']}>Zapraszamy do umówienia się na bezpłatną wycenę i projekt.</div>
                        <div className={styles['kontakt-content']}>888 333 891</div>
                        <div className={styles['kontakt-content']}>biuro@nordszczecin.pl</div>
                    </div>
                    </>
                    :
                    <>
                    
                    </>}
                </div>
                {size.width > 600 ? 
                    <>
                    
                    </>
                    :
                    <>
                    <div id='animated-text' className={styles['hero-section-text-animated']}>
                        <div className={styles['kontakt-content']}>Nasza oferta obejmuje projektowanie, produkcję i montaż mebli, takich jak meble kuchenne, szafy, garderoby oraz meble biurowe w województwie <span className={['accent']}>Zachodniopomorskim</span>.</div>
                        <div className={styles['kontakt-content']}>Zapraszamy do umówienia się na bezpłatną wycenę i projekt.</div>
                        <div className={styles['kontakt-content']}>888 333 891</div>
                        <div className={styles['kontakt-content']}>biuro@nordszczecin.pl</div>
                    </div>
                    </>}
            </div>



            {/*Footer*/}

            <Footer />


        </>
    )
}
